### ISSUE TITLE
Reoccuring Event showing on the next day

### ISSUE THREAD

**Issue by efbenson** [MMRIZE/MMM-CalendarExt3#150] opened 2024-05-02 15:10 UTC
I suspect it is related to timezone offsets.  I have 2 reoccuring Dance classes for my kids.  One is at 6-7PM NY time the other 7-8PM NY time on Thursdays.  The second one 7-8 shows on friday the right time.  I have pulled the events from the ICSs and converted them to JSON to better figure out what is going on.  I would guess because the 7-8 one is would be 00:00:00Z-5 (during daylight savings) it would track to the next day.

Throwing the start dates into moment: 
``` terminal
> moment('20240104T180000')
Moment<2024-01-04T18:00:00-05:00>
> moment('20240104T190000')
Moment<2024-01-04T19:00:00-05:00>
```

``` JSONC
       // Shows on Thursday (Correct)

       {
        "DTSTART;TZID=America/New_York": "20240104T180000",
        "DTEND;TZID=America/New_York": "20240104T190000",
        "RRULE": "FREQ=WEEKLY;WKST=MO;UNTIL=20240613T035959Z",
        "EXDATE;TZID=America/New_York": "20240328T180000",
        "DTSTAMP": "20240502T144525Z",
        "UID": "64ojgp35copjcbb36hgjcb9k60o3gbb16kqm8b9jc4pjgcpj6grjgc9h68@google.com",
        "CREATED": "20231231T165940Z",
        "LAST-MODIFIED": "20240409T001503Z",
        "SEQUENCE": "0",
        "STATUS": "CONFIRMED",
        "SUMMARY": "Dance",
        "TRANSP": "OPAQUE"
      }


     // Shows on Friday (Wrong)
       {
          "DTSTART;TZID=America/New_York": "20240104T190000",
          "DTEND;TZID=America/New_York": "20240104T200000",
          "RRULE": "FREQ=WEEKLY;WKST=MO;UNTIL=20240613T035959Z",
          "EXDATE;TZID=America/New_York": [
            "20240425T190000",
            "20240328T190000"
          ],
          "DTSTAMP": "20240502T013958Z",
          "UID": "6dhj6p9h60p36bb3cos30b9k70p36b9o71ijcbb5c8sj4cr175ij0db2ck@google.com",
          "CREATED": "20231231T165958Z",
          "LAST-MODIFIED": "20240409T001511Z",
          "SEQUENCE": "1",
          "STATUS": "CONFIRMED",
          "SUMMARY": "Dance",
          "TRANSP": "OPAQUE"
        },
   ```
   
   If you can point me to what code might be involved with it I can take a whack it it.  It looks like its in the CX3_Shared file?

**Comment by eouia** [comment] 2024-05-02 15:21
Recently (Since MM 2.27) I meet this issue often. The reason is the default MM's handling RRULE is not perfect. It sends wrong notifications of Repeated-Fullday-Event-WithTimeZone.

Did you update to the last CX3 1.8.3? I think I solve that issue on that version.

**Comment by efbenson** [comment] 2024-05-02 16:30
Yep on the latest version still and still a problem.

**Comment by eouia** [comment] 2024-05-02 21:54
Could you share me the real ics file or url?(eouia0819)
And also your config.js.

**Comment by epascua2** [comment] 2024-05-07 23:14
I am also having this same issue with reoccuring events being a duplicate the next day. I imagine I am on the latest versions because I just got this set up only a couple of days ago, but Im not sure how I can check what cx3 version I am on

**Comment by eouia** [comment] 2024-05-15 07:21
After studying several similar cases, I dare to say, this symptom is caused by MM's default calendar module's error(Since MM 2.27). It could not handle the recurrent events well. 

I'll close this issue.

**Closed by eouia** 2024-05-15 07:21 UTC
